version: "3.9"
services:
  pgdb:
    image: postgres:latest
    container_name: POSTGRES_SERVICE
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5433
    restart: unless-stopped
  web:
    build: .
    container_name: DJANGO_APP
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/medicalapp
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - pgdb

volumes:
  postgres_data: