# Generated by Django 4.2.5 on 2023-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('date_of_treatment', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_of_treatment'],
            },
        ),
    ]
